/*
   3D model generated by Jo Map Editor v6.0
*/

#ifndef __3D_ASTEROID_H__
# define __3D_ASTEROID_H__

static POINT    PointAsteroid[] =
{
	{-5179653, 6154952, 4459926},
	{-436246, 6780992, 6229337},
	{3600237, 5657687, 4435084},
	{-5129380, -1630767, 6059867},
	{-242895, -1676393, 7913104},
	{4450190, -610982, 6075592},
	{-3354267, 4310362, -1478078},
	{-436246, 4936403, -1618802},
	{3351708, 3622473, -1455407},
	{-4699430, -1009608, -1597693},
	{-242895, -558674, -1747948},
	{4788082, -465679, -1607068},
	{-4032636, 5079503, 2398046},
	{-392541, 5608333, 2398046},
	{3816658, 4310708, 2399882},
	{5179646, -414233, 2887719},
	{-227040, -1031460, 2893082},
	{-5134159, -1412372, 2893082},
	{-3060803, 4376632, -5058863},
	{-418033, 4914249, -5708400},
	{2782760, 3785904, -5039395},
	{-4510462, -671263, -6345257},
	{-251474, -284021, -7038784},
	{4292355, -204161, -6353308},
};

static POLYGON    PolygonAsteroid[] =
{
	{{-23481, 11678, 60057}, {0, 3, 4, 4}},
	{{-2477, 12989, 64185}, {4, 1, 0, 0}},
	{{-209, 14712, 63864}, {1, 4, 5, 5}},
	{{23658, 14404, 59395}, {5, 2, 1, 1}},
	{{-15571, 16711, -61426}, {18, 19, 22, 22}},
	{{-2470, 17386, -63137}, {22, 21, 18, 18}},
	{{-3067, 18409, -62822}, {19, 20, 23, 23}},
	{{13172, 19818, -61059}, {23, 22, 19, 19}},
	{{-4436, 59913, -26181}, {0, 1, 13, 13}},
	{{6881, 63032, -16567}, {13, 12, 0, 0}},
	{{5609, 61597, -21666}, {1, 2, 14, 14}},
	{{14522, 60653, -20139}, {14, 13, 1, 1}},
	{{-9561, 59834, -24962}, {12, 13, 7, 7}},
	{{5092, 64218, -12032}, {7, 6, 12, 12}},
	{{6881, 63032, -16567}, {13, 14, 8, 8}},
	{{20198, 61197, -11907}, {8, 7, 13, 13}},
	{{63543, 15708, 3224}, {2, 5, 15, 15}},
	{{63569, 15577, 3289}, {15, 14, 2, 2}},
	{{62541, 18494, -6435}, {14, 15, 11, 11}},
	{{62082, 19385, -8054}, {11, 8, 14, 14}},
	{{9181, -64703, -4941}, {5, 4, 16, 16}},
	{{7012, -64808, -6730}, {16, 15, 5, 5}},
	{{7431, -64670, -7575}, {4, 3, 17, 17}},
	{{4050, -65142, -5924}, {17, 16, 4, 4}},
	{{5714, -65234, -2595}, {15, 16, 10, 10}},
	{{5511, -65110, -5033}, {10, 11, 15, 15}},
	{{7012, -64808, -6730}, {16, 17, 9, 9}},
	{{5675, -65018, -5970}, {9, 10, 16, 16}},
	{{-64821, 6914, -6737}, {3, 0, 12, 12}},
	{{-62711, 2896, -18808}, {12, 17, 3, 3}},
	{{-64310, 12202, -3171}, {17, 12, 6, 6}},
	{{-63622, 12189, -9941}, {6, 9, 17, 17}},
	{{-13769, 64074, -406}, {6, 7, 19, 19}},
	{{-13035, 64225, 117}, {19, 18, 6, 6}},
	{{6435, -65070, -4384}, {10, 9, 21, 21}},
	{{5380, -65227, -3394}, {21, 22, 10, 10}},
	{{-63333, 16121, -4888}, {9, 6, 18, 18}},
	{{-62894, 18369, -1192}, {18, 21, 9, 9}},
	{{21495, 61905, -589}, {7, 8, 20, 20}},
	{{21830, 61793, -235}, {20, 19, 7, 7}},
	{{61571, 21830, -5229}, {8, 11, 23, 23}},
	{{59840, 25388, -8342}, {23, 20, 8, 8}},
	{{1304, -65437, -3401}, {11, 10, 22, 22}},
	{{1717, -65404, -3781}, {22, 23, 11, 11}},
};

static ATTR    AttributeAsteroid[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, 0, No_Palet, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprNoflip, UseLight),
};

jo_3d_mesh    MeshAsteroid =
{
	.data =
	{
		PointAsteroid,
		24,
		PolygonAsteroid,
		44,
		AttributeAsteroid
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_asteroid_mesh(void)
{
	jo_3d_mesh_draw(&MeshAsteroid);
}

#endif /* !__3D_ASTEROID_H__ */
